name: Commitlint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:
jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commitlint
        shell: bash
        run: |
            npm install
            echo $(git log -1 --pretty=format:"%s") | npx commitlint --verbose --strict