name: MSVC-Windows

on:
  push:
    branches: [ senpai ]
  pull_request:
    branches: [ senpai ]

  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        standard: [ 90, 99, 11, 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_C_STANDARD=${{ matrix.standard }} \
                $GITHUB_WORKSPACE

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config Debug
          ./thicc_test
          ctest -VV --output-on-failure -C Debug